name: LonelyBull
options:
  bundleIdPrefix: com.vohefett
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1,2"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
targets:
  LonelyBull:
    type: application
    platform: iOS
    sources:
      - path: LonelyBull
        excludes:
          - "**/.DS_Store"
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vohefett.LonelyBull
        PRODUCT_NAME: LonelyBull
        INFOPLIST_FILE: LonelyBull/Info.plist
        GENERATE_INFOPLIST_FILE: false
        CURRENT_PROJECT_VERSION: 11
        MARKETING_VERSION: "1.2.0"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
        ENABLE_TESTABILITY: YES
        INFOPLIST_KEY_CFBundleDisplayName: LonelyBull
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
    scheme:
      testTargets:
        - LonelyBullTests
  LonelyBullTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: LonelyBullTests
    dependencies:
      - target: LonelyBull
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vohefett.LonelyBullTests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/LonelyBull.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/LonelyBull"
        BUNDLE_LOADER: "$(TEST_HOST)"
